spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: 0oagdgf573MKeT1R40h7
            client-secret: eZnRYj6o2MPd8pbxKEr8Y1qvvoYxWQW7-989irIt
            scope: openid email profile
        provider:
          okta:
            issuer-uri: https://dev-555911.oktapreview.com/oauth2/default